# This workflow builds and deploys a Jekyll site to GitHub Pages
# using GitHub Actions. It is triggered on pushes to the master branch
# or manually via the Actions tab.

name: Deploy Jekyll site to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["master"]

  # Allows manual triggering of the workflow from the Actions tab
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN to allow publishing to GitHub Pages
permissions:
  contents: read           # Required to clone the repository
  pages: write             # Required to publish to GitHub Pages
  id-token: write          # Required for OIDC authentication
  deployments: write       # Required by deploy-pages@v4

# Only allow one deploy at a time to avoid collisions
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build the Jekyll site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'        # Matches your local Ruby version or .ruby-version file
          bundler-cache: true        # Automatically installs and caches gems
          cache-version: 0           # Bump if you want to force cache refresh

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload build output as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages         # Name must match the one used in the deploy step

  # Deploy the site to GitHub Pages
  deploy:
    needs: build                     # Waits for the build job to finish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
